### ISSUE TITLE
It's better to upgrade package-lock.json also.

### ISSUE THREAD

**Issue by abcfy2** [pgsandstrom/package-json-upgrade#5]
I think it's better to use `npm install` or `npm update` to modify `package.json`. Because the command will modify both `package.json` and `package-lock.json`, and also upgrade `node_module/`.

Only modify `package.json` not affect current project.

**Comment by pgsandstrom** [comment]
It is a bit complicated, since `npm install` and `npm update` can take quite some time. It might require some queue logic so several commands can be launched without waiting for the install. It would also require some logic to detect if the project is using npm lock file or yarn lock file.

I'll consider this when it is time for a v2.0 release, but it will require some thinking. Thanks for the feedback, it is always appreciated!
